### ISSUE TITLE
File drag-n-drop prompt wrong color

### ISSUE THREAD

**Issue by robmonte** [LanikSJ/slack-dark-mode#209]
**Describe the bug**
Theme not applied to file drag-n-drop prompt

**To Reproduce**
1\. Drag file into slack channel or DM
2\. Observe issue

**Expected behavior**
It should be a dark overlay instead of bright white

**Screenshots**
![image](https://user-images.githubusercontent.com/17119716/64208473-8088a100-ce64-11e9-9528-8cfc0e190f53.png)

**Desktop (please complete the following information):**

-   OS: macOS
-   Slack Version: 4.0.3

**Additional context**
N/A

**Comment by LanikSJ** [comment]
I can reproduce this but I'm not able to find the CSS element for it. 

Thank you for the bug report keep them coming.

**Comment by dhruvasagar** [comment]
@LanikSJ I found the css element it's `.p-message_pane_drag_overlay`. But the element only appears when you drag a file, don't know of any other way to simulate it.

I found this reference css : https://git.vetruvet.com/vetruvet/dotfiles/commit/c6828620465d56ccd697c35980b688c8b544e675?expanded=1&w=1

I added these styles :
```css
.p-message_pane_drag_overlay, .p-message_pane_drag_overlay--night {
  color: var(--main-text);
  background-color: rgba(66,66,66, 0.95);
}
```
Got it to have a dark background with those, though it still flashes white background first and then goes dark. The white flash is a bit annoying but can't figure out how to fix that.
